# Generated by Django 3.1 on 2020-08-21 02:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAplicacion', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=0, verbose_name='id de usuario login')),
                ('FechaSubida', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de carga')),
                ('Estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('AplicacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.aplicacion', verbose_name='Aplicacion')),
            ],
            options={
                'verbose_name': 'Archivo carga',
                'verbose_name_plural': 'Archivos de carga',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresitio', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipoproceso', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('AplicacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.aplicacion', verbose_name='Aplicacion')),
            ],
            options={
                'verbose_name': 'Tipo Proceso',
                'verbose_name_plural': 'Tipos de Procesos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipoArchivoCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipoCarga', models.CharField(max_length=100, verbose_name='Nombre')),
                ('limiteArchivo', models.IntegerField(default=0, verbose_name='Limite')),
                ('TipoArchivopermitido', models.CharField(max_length=20, verbose_name='Tipo archivo permitido')),
                ('tipoProcesoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoproceso', verbose_name='TipoProceso')),
            ],
            options={
                'verbose_name': 'Tipo archivo carga',
                'verbose_name_plural': 'Tipos de archivos de carga',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoCargaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArcConfigSitio', models.FileField(upload_to='ConfSitio/<function user_directory_path at 0x03EFA1D8>', verbose_name='Config. actual de sitios')),
                ('ArcBaseDF', models.FileField(upload_to='BaseDF/<function user_directory_path at 0x03EFA1D8>', verbose_name='Base DF')),
                ('ArcConfigInicio', models.FileField(upload_to='ConfiInical/<function user_directory_path at 0x03EFA1D8>', verbose_name='Config. inicio')),
                ('ArchivoCargaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.archivocarga', verbose_name='Archivo de carga')),
                ('tipoArchivoCargaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoarchivocarga', verbose_name='tipo de archivo')),
            ],
            options={
                'verbose_name': 'Archivo de carga con detalle',
                'verbose_name_plural': 'Archivos de cargas con detalle',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='IdSitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sitios', verbose_name='Sitios'),
        ),
    ]
