# Generated by Django 3.1 on 2020-08-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproceso',
            options={'ordering': ['id'], 'verbose_name': 'Tipo Proceso', 'verbose_name_plural': 'Tipos Procesos'},
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcBaseDF',
            field=models.FileField(blank=True, max_length=300, upload_to='BaseDF/<function user_directory_path at 0x0485A1D8>', verbose_name='Base DF'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcConfigInicio',
            field=models.FileField(blank=True, max_length=300, upload_to='ConfiInical/<function user_directory_path at 0x0485A1D8>', verbose_name='Config. inicio'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcConfigSitio',
            field=models.FileField(blank=True, max_length=300, upload_to='ConfSitio/<function user_directory_path at 0x0485A1D8>', verbose_name='Config. actual de sitios'),
        ),
        migrations.AlterField(
            model_name='tipoarchivocarga',
            name='tipoProcesoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoproceso', verbose_name='Tipo Proceso'),
        ),
        migrations.AlterField(
            model_name='tipoproceso',
            name='AplicacionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.aplicacion', verbose_name='Tipo proceso'),
        ),
    ]
