# Generated by Django 3.1 on 2020-08-21 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200820_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocarga',
            name='FechaSubida',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcBaseDF',
            field=models.FileField(max_length=300, upload_to='BaseDF/%Y/%m/%d', verbose_name='Base DF'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcConfigInicio',
            field=models.FileField(max_length=300, upload_to='ConfiInical/%Y/%m/%d', verbose_name='Config. inicio'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArcConfigSitio',
            field=models.FileField(max_length=300, upload_to='ConfSitio/%Y/%m/%d', verbose_name='Config. actual de sitios'),
        ),
    ]
