# Generated by Django 3.1 on 2020-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200821_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocargadetail',
            name='ArcBaseDF',
        ),
        migrations.RemoveField(
            model_name='archivocargadetail',
            name='ArcConfigInicio',
        ),
        migrations.RemoveField(
            model_name='archivocargadetail',
            name='ArcConfigSitio',
        ),
        migrations.AddField(
            model_name='archivocargadetail',
            name='ArchivoCheck',
            field=models.FileField(blank=True, max_length=300, upload_to='CheckValidacion/%Y_%m_%d', verbose_name='Archivos'),
        ),
        migrations.AddField(
            model_name='archivocargadetail',
            name='ExtencionArchivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Extencion de archivo'),
        ),
        migrations.AddField(
            model_name='archivocargadetail',
            name='NombreArchivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Archivo'),
        )
    ]
