# Generated by Django 3.1 on 2020-08-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200821_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarchivocarga',
            name='Validar',
            field=models.BooleanField(default=False, verbose_name='a validar'),
        ),
        migrations.AlterField(
            model_name='archivocargadetail',
            name='ArchivoCheck',
            field=models.FileField(blank=True, max_length=300, upload_to='%d_%m_%Y', verbose_name='Archivos'),
        ),
        migrations.AlterField(
            model_name='tipoarchivocarga',
            name='TipoArchivopermitido',
            field=models.CharField(default='.xlsx|.xls', max_length=20, verbose_name='Tipo archivo permitido'),
        ),
        migrations.AlterField(
            model_name='tipoproceso',
            name='AplicacionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.aplicacion', verbose_name='Aplicacion'),
        ),
    ]
