# Generated by Django 3.1 on 2020-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20200910_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarchivocarga',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=100, verbose_name='abreviatura'),
        ),
    ]
