# Generated by Django 3.1 on 2020-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_tipoarchivocarga_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproceso',
            name='nombretipoproceso',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
